### PR TITLE
Feature: pcr free alignment

### PR DESCRIPTION
**Pull request by bryce-turner**
This adds two new workflows designed with pcr free alignment in mind. The primary workflow uses bwa-mem2 and marks duplicates at the lane level before merging into one alignment file. We also have the fq2bam workflow which is gpu-accelerated, but this isn't called in the main.jst as it will likely be bottlenecked on our compute cluster.

### CODE REVIEW

**Comment by bryce-turner** [comment]
This resolves issue #384

**Review by PedalheadPHX — COMMENTED** [review]
@bryce-turner Do these support fasterQ?

**Comment by bryce-turner** [comment]
Good point, this is not configured for fasterq support, I'll add that now.

**Review by PedalheadPHX — APPROVED** [review]
Good

**Pull request merged**
